#!/usr/bin/env python3
"""Iteration 73: four high-intent SEO keyword pages targeting long-tail searches.
Reuses build_post() from make_blog.py. Writes to site/blog/{slug}.html."""

from make_blog import build_post

jobs = [
    dict(
        slug='nis2-checklist-pdf',
        meta_desc='Free NIS2 compliance checklist: 25 checks covering risk management, incident reporting, supply chain and documentation. Read online or print as PDF. Updated for 2026.',
        badge_label='NIS2 CHECKLIST',
        h1='NIS2 Compliance Checklist:<br>25 Checks Before Your Next Audit',
        subtitle='A practical, printable checklist covering every NIS2 Article 21 measure a small agency needs — risk management, incident handling, supply chain security and documentation.',
        reading_time='8 minutes',
        cta_product=('Run the Free NIS2 Scan →', '/nis2-check'),
        cta_secondary=('NIS2 E-Book →', '/#products',
                       'Our NIS2 e-book expands this checklist into a full implementation guide with contract clauses, incident report templates and a 30-day plan.'),
        sections=[
            ('who-must-comply',
             'NIS2 (Directive (EU) 2022/2555) is the EU\'s cybersecurity rulebook for essential and important entities. If your agency builds or maintains digital infrastructure for clients — hosting, e-commerce, SaaS, networks — you are likely in scope either directly or through your clients\' supply-chain obligations under Article 21(2)(d). Member states had to transpose the directive by October 17, 2024, and enforcement is active across the EU in 2026.',
             [
                ('🏢', 'Essential Entities', 'Energy, transport, banking, health, digital infrastructure, public administration. Stricter supervision, fines up to €10M or 2% of global turnover.'),
                ('📦', 'Important Entities', 'Postal services, waste management, chemicals, food, manufacturing, digital providers. Fines up to €7M or 1.4% of turnover.'),
                ('🔗', 'Supply Chain', 'Even if your agency is too small to be in scope itself, essential-entity clients must verify YOUR security under Article 21(2)(d). A completed checklist is your proof.'),
             ]),
            ('the-checklist',
             ['Work through all 25 checks. Each maps to an Article 21 measure. Checks marked ⚠️ are the ones auditors find missing most often at small organisations.'],
             [
                ('🛡️', '1. Risk Analysis & IS Policy (Art. 21(2)(a))', 'Documented information-security policy approved by management. ⚠️ Risk assessment methodology actually written down, not just implied. Annual review scheduled.'),
                ('🖥️', '2. Incident Handling (Art. 21(2)(b))', 'Incident response plan with roles and contact lists. ⚠️ 24-hour initial / 72-hour notification / final-report timeline documented. Post-incident review process defined.'),
                ('🔁', '3. Business Continuity (Art. 21(2)(c))', 'Backups tested by restore, not just taken. Disaster-recovery RTO/RPO targets set. Alternate communication channel identified.'),
                ('🔗', '4. Supply Chain Security (Art. 21(2)(d))', 'Vendor register with security assessment per vendor. Security clauses in contracts (hosting, plugins, freelancers). Exit plan for critical vendors.'),
                ('🔐', '5. Acquisition & Maintenance (Art. 21(2)(e))', 'Vulnerability disclosure policy published. Patch-management routine with maximum timeframes. Secure development lifecycle for shipped code.'),
                ('📊', '6. Effectiveness Assessment (Art. 21(2)(f))', 'Annual security audit or self-assessment. Metrics tracked (patch latency, incident counts). Management reviews results on record.'),
                ('🎓', '7. Cyber Hygiene & Training (Art. 21(2)(g))', 'Security awareness training at least yearly. MFA enforced everywhere possible. Password manager mandated. Least-privilege access reviewed quarterly.'),
                ('🔒', '8. Cryptography & Encryption (Art. 21(2)(h))', 'Encryption in transit (TLS 1.2+) and at rest for personal/client data. Key management documented. Encrypted backups.'),
                ('👥', '9. HR, Access Control & Asset Mgmt (Art. 21(2)(i))', 'Onboarding/offboarding checklist revokes access immediately. Asset inventory of hardware, software and data flows. Clean-desk and device policy.'),
                ('📝', '10. Documentation & Evidence', 'Every policy above dated, versioned and signed off. ⚠️ Evidence folder: training logs, backup test reports, patch logs, incident post-mortems. Auditors ask for evidence, not intentions.'),
             ]),
            ('reporting-timelines',
             'Article 23 sets strict reporting duties for entities in scope. An early warning within 24 hours of becoming aware of a significant incident, an incident notification within 72 hours, an intermediate report on request, and a final report within one month. Even if your agency is not directly in scope, your essential-entity clients will pass these deadlines down to you contractually — knowing the clock starts at awareness, not at confirmation, is what keeps their notifications accurate.',
             None),
            ('how-to-use-this-checklist',
             'Print this page (Ctrl/Cmd+P produces a clean PDF). Score each check as Pass / Partial / Fail. Any Fail becomes a task with an owner and a deadline. Re-run the checklist quarterly — NIS2 requires policies to stay effective under Article 21(1), not just exist once. For automated help, run our free NIS2 scan against any site you operate: it checks the externally visible technical controls (TLS, headers, exposed files) that map to checks 5, 7 and 8.',
             None),
        ],
        faqs=[
            ('Is there an official NIS2 PDF checklist?',
             'ENISA and national CSIRTs publish guidance documents, but there is no single official checklist PDF. This page is a practical consolidation of the ten Article 21 measures into 25 verifiable checks — print it with Ctrl/Cmd+P.'),
            ('Does my small agency really fall under NIS2?',
             'Possibly not directly — size caps matter (essential: typically 50+ employees; important: medium-sized). But NIS2 reaches small agencies through the supply chain: larger clients must assess your security, and many now demand documented evidence before signing.'),
            ('What happens if we ignore it?',
             'For entities in scope: fines up to €10M/2% turnover (essential) or €7M/1.4% (important), plus management liability under Article 20. For out-of-scope agencies: losing enterprise clients who require evidence of security practices.'),
            ('How is NIS2 different from GDPR?',
             'GDPR protects personal data; NIS2 protects network and information systems. They overlap operationally (incident response, encryption, vendor management) but are separate laws with separate reporting channels. See our GDPR vs NIS2 overlap guide.'),
        ],
        related_posts=[
            ('NIS2 · GUIDE', 'NIS2 Readiness Guide for Small Agencies', '/blog/nis2-readiness-guide'),
            ('NIS2 · INCIDENTS', 'NIS2 Incident Report Checklist', '/blog/nis2-incident-report-checklist'),
            ('NIS2 · SUPPLY CHAIN', 'NIS2 Supply Chain Security Requirements', '/blog/nis2-supply-chain-security'),
            ('GDPR · OVERLAP', 'GDPR vs NIS2: Where the Two Laws Overlap', '/blog/gdpr-vs-nis2-overlap'),
        ],
    ),
    dict(
        slug='eaa-deadline-2026',
        meta_desc='EAA deadline explained: June 28, 2025 has passed — here is exactly what is enforced in 2026, which products are covered, exemptions, and what to do if your site is non-compliant today.',
        badge_label='EAA DEADLINE',
        h1='EAA Deadline: What Is Enforced<br>Right Now in 2026',
        subtitle='The June 28, 2025 deadline has passed. Here is what the European Accessibility Act requires today, who is exempt, what fines look like per country, and the fastest path to compliance.',
        reading_time='6 minutes',
        cta_product=('Scan Your Site Free →', '/scan'),
        cta_secondary=('EAA E-Book →', '/#products',
                       'Our EAA e-book turns the legal text into a 14-day fix plan with tool recommendations and a ready-to-fill accessibility statement.'),
        sections=[
            ('deadline-status',
             'The European Accessibility Act (Directive (EU) 2019/882) required member states to apply its provisions from June 28, 2025. That date has passed: enforcement is live in every member state, market-surveillance authorities are operating, and the first fines have been issued — including penalties reported in Sweden (~€900K) and Spain (~€600K). In 2026 the question is no longer "when do I need to comply?" but "how fast can I document compliance?".',
             [
                ('📅', 'Already Passed', 'June 28, 2025 — obligations apply. Services contracted after this date must conform to WCAG 2.1 AA / EN 301 549.'),
                ('⏳', 'Service Continuity Grace', 'Pre-existing services may continue until they undergo "significant change" — but redesigns, replatforms or major updates reset the clock to full conformance.'),
                ('🏗️', 'Built Environment Exception', 'Some physical-structure exemptions run to 2030 in certain states. Digital services get no such extension.'),
             ]),
            ('who-is-covered',
             'The EAA applies to products and services placed on the EU market after the deadline: e-commerce sites, banking services, e-books, ticketing machines, smartphones, TV equipment, and telecom services. For web agencies the key trigger is e-commerce: any online shop you build, host or maintain for an EU seller is in scope. Micro-enterprises (fewer than 10 employees AND under €2M annual turnover) offering SERVICES are exempt — but note this exemption does not extend to the products they sell or resell.',
             None),
            ('what-enforcement-looks-like',
             'Each member state designated market-surveillance authorities. Enforcement so far follows a pattern: complaints from users trigger investigation, authorities issue corrective orders with deadlines, and fines follow for continued non-conformance. Several countries also allow consumer organisations to bring actions. The practical consequence for agencies: a client\'s accessibility complaint letter lands on YOUR desk first, because the fix lives in your codebase.',
             [
                ('🇸🇪', 'Sweden', 'Fines up to ~€900K reported for non-conforming services after the deadline.'),
                ('🇪🇸', 'Spain', '~€600K penalties issued; consumer groups actively testing retail sites.'),
                ('🇩🇪', 'Germany', 'BFSG enforcement via Marktüberwachungsstellen; BITV-style testing methodologies applied to private sector for the first time.'),
                ('🇫🇷', 'France', 'Existing RGAA enforcement tightened; EAA obligations folded into the same monitoring cycle.'),
             ]),
            ('if-you-are-non-compliant-now',
             'Do not panic-redesign. Regulators respond to documented good-faith remediation far better than to silence. The sequence that works: (1) run an automated scan to find the mechanical failures — contrast, alt text, headings, labels; (2) fix those, they are usually days of work; (3) publish an honest accessibility statement stating partial conformance with known issues and a feedback channel — this alone satisfies the documentation requirement while deeper work continues; (4) schedule manual screen-reader testing for complex flows like checkout. Our free scanner covers step 1 in about two minutes for most sites.',
             None),
        ],
        faqs=[
            ('Is there a new EAA deadline after June 2025?',
             'No. June 28, 2025 was the final application date. There is no second grace period for digital services. The only remaining transitions concern pre-existing service continuity and specific built-environment items in some member states.'),
            ('My site was launched before the deadline — am I safe?',
             'Not permanently. Self-service pre-existing contracts enjoy continuity until significant change, but authorities interpret "significant change" broadly: a redesign, new checkout flow or platform migration ends the grace period. And user complaints trigger scrutiny regardless of launch date.'),
            ('Are micro-businesses exempt?',
             'Services-only exemption applies if you have fewer than 10 employees and under €2M turnover. It does NOT cover products you sell, and it does not stop enterprise clients demanding WCAG conformance contractually anyway.'),
            ('What standard must we meet?',
             'The presumption of conformity is tied to EN 301 549, which incorporates WCAG 2.1 Level AA for web content. Meeting WCAG 2.1 AA plus the statement and feedback-channel requirements covers the overwhelming majority of EAA obligations for websites.'),
        ],
        related_posts=[
            ('EAA · CHECKLIST', 'EAA Accessibility Checklist: 10 Steps', '/blog/eaa-accessibility-checklist'),
            ('EAA · ENFORCEMENT', 'EAA Enforcement in 2026: Fines and Cases', '/blog/eaa-enforcement-2026'),
            ('EAA · STATEMENTS', 'How to Write an Accessibility Statement', '/blog/how-to-write-accessibility-statement'),
            ('EAA · OVERLAYS', 'Accessibility Overlays and the EAA', '/blog/accessibility-overlays-eaa'),
        ],
    ),
    dict(
        slug='gdpr-website-compliance-checklist',
        meta_desc='GDPR website compliance checklist: 18 checks covering cookie consent, privacy policy, forms, analytics, processors and data subject rights. Free and printable.',
        badge_label='GDPR CHECKLIST',
        h1='GDPR Website Compliance Checklist:<br>18 Checks Every Site Should Pass',
        subtitle='Cookie banners are the visible tip. These 18 checks cover everything a compliant website actually needs — consent, processors, forms, retention and data subject rights.',
        reading_time='7 minutes',
        cta_product=('Check Your Cookies Free →', '/cookie-check'),
        cta_secondary=('GDPR E-Book →', '/#products',
                       'Our GDPR e-book includes DPA templates, a records-of-processing sheet and an 8-clause contract pack for agencies.'),
        sections=[
            ('consent-and-cookies',
             'Consent is where most website GDPR failures concentrate, and where regulators fine first. The ePrivacy Directive requires consent for non-essential cookies BEFORE they are set — meaning no tracking scripts fire until the visitor clicks accept. Pre-ticked boxes are invalid (Planet49 ruling), rejecting must be as easy as accepting, and the banner may not nudge users toward yes.',
             [
                ('✅', '1. Consent before scripts', 'No analytics/marketing tag fires pre-consent. Verify in DevTools: block the banner and confirm no _ga/_fbp/gtag requests appear.'),
                ('✅', '2. Equal reject button', '"Reject all" is equally prominent and clickable as "Accept all". No hidden reject links in grey footers.'),
                ('✅', '3. Granular choices', 'Separate categories (necessary / preferences / statistics / marketing), not one all-or-nothing toggle.'),
                ('⚠️', '4. Consent log', 'Store timestamp, categories chosen, banner version. You must be able to prove consent, not just obtain it.'),
                ('⚠️', '5. Legit interest assessed', 'Where you rely on legitimate interest instead of consent, a documented balancing test exists.'),
                ('✅', '6. Cookie list & lifetimes', 'Cookie policy lists every cookie, purpose and expiry — regenerate it when tags change.'),
             ]),
            ('transparency-and-content',
             'Users must be able to find out what happens to their data without effort. That means a privacy notice written in plain language, reachable from every page, that names each role correctly: you are the controller for your own site data, and often a processor for client data if you run client sites.',
             [
                ('✅', '7. Privacy policy current', 'Names legal basis per processing activity, retention periods, third countries transfers, and your DPO/contact.'),
                ('✅', '8. Policy reachable everywhere', 'Linked from footer AND from the cookie banner and every form that collects data.'),
                ('✅', '9. Forms declare purpose', 'Each form says what the data will be used for and links to the policy. No "we may use it for marketing" surprises.'),
                ('⚠️', '10. No unnecessary collection', 'Fields collecting data you never use are a liability, not an asset. Delete them.'),
             ]),
            ('processors-and-transfers',
             'Every third-party tool that touches personal data — analytics, email marketing, hosting, fonts, chat widgets — needs a Data Processing Agreement and a transfer mechanism if data leaves the EU. US-based tools need an EU-US Data Privacy Framework certification or SCCs. Google Analytics type tools remain legally sensitive in several member states after the Schrems II line of cases.',
             [
                ('✅', '11. Processor inventory', 'List every tool touching personal data with its role and DPA status.'),
                ('✅', '12. DPAs signed', 'Standard contractual clauses or provider DPAs on file for each processor.'),
                ('⚠️', '13. Transfer mechanism', 'Non-EU processors: DPF certified or SCCs + transfer impact assessment documented.'),
                ('✅', '14. Sub-processors known', 'You know who your vendors sub-contract, and object rights are respected.'),
             ]),
            ('rights-and-response',
             'Data subject rights are operational, not theoretical: when someone emails "delete my data" you have one month to respond (Art. 12(3)). Sites fail audits because nobody knows where the data lives or who answers such requests.',
             [
                ('✅', '15. Request channel', 'A named contact (privacy@…) that is monitored. Response within one month, documented.'),
                ('⚠️', '16. Access/deletion procedure', 'Written steps: identify the person across systems, export, delete, confirm. Test it once a year.'),
                ('✅', '17. Breach plan', '72-hour supervisory-authority notification path documented, with templates ready before an incident.'),
                ('✅', '18. Retention enforced', 'Old form submissions, exports and CRM entries auto-delete on schedule. Indefinite storage is indefensible.'),
             ]),
        ],
        faqs=[
            ('Is a cookie banner enough for GDPR compliance?',
             'No. The banner handles consent (checks 1–6 above), but processors, transparency, rights-handling and retention are independent requirements — and they are where fines actually originate.'),
            ('Do I need consent for anonymous analytics?',
             'In most member states, yes, if cookies are involved. Some tools without cookies and with IP anonymisation can rely on legitimate interest, but that requires the documented balancing test in check 5. When in doubt, ask consent — it is always defensible.'),
            ('What is the biggest fine risk for a normal website?',
             'Practically: ignoring data subject requests and having no processor agreements. Both are trivially provable violations that regulators encounter constantly, unlike exotic cross-border questions.'),
            ('We run client websites — what is OUR exposure?',
             'You are usually a processor for client data: you need DPAs with clients (see our DPA guide), and your own site practices signal whether you take GDPR seriously. Enterprise clients check.'),
        ],
        related_posts=[
            ('GDPR · DPA', 'GDPR Data Processing Agreement for Web Agencies', '/blog/gdpr-dpa-web-agencies'),
            ('GDPR · FINES', 'GDPR Fines in 2026: Trends and Numbers', '/blog/gdpr-fines-2026'),
            ('COOKIES · TOOL', 'Free Cookie Consent Checker', '/cookie-check'),
            ('GDPR · OVERLAP', 'GDPR vs NIS2: Where the Two Laws Overlap', '/blog/gdpr-vs-nis2-overlap'),
        ],
    ),
    dict(
        slug='free-accessibility-testing-tools',
        meta_desc='Comparison of free accessibility testing tools in 2026: WAVE, axe DevTools, Lighthouse, Accessibility Insights, NVDA and automated scanners — what each catches, and what none of them catch.',
        badge_label='TOOLS COMPARISON',
        h1='Free Accessibility Testing Tools:<br>What Each One Actually Catches',
        subtitle="WAVE, axe DevTools, Lighthouse, Accessibility Insights and automated scanners compared — coverage, strengths, blind spots, and how to combine them into a workflow that holds up.",
        reading_time='8 minutes',
        cta_product=('Try Our Free Scanner →', '/scan'),
        cta_secondary=('EAA E-Book →', '/#products',
                       'Our EAA e-book includes a full tool-by-tool testing protocol mapped to each WCAG criterion.'),
        sections=[
            ('why-more-than-one-tool',
             'Automated tools detect roughly 30–40% of WCAG failures — the same 30–40%, mostly. Running three overlapping scanners gives you false confidence without new coverage. The strategy that works is layering tools with different blind spots: DOM-level analysers for code defects, visual tools for contrast and focus, a real screen reader for the experience, and manual keyboard testing for interaction. Below: what each free tool genuinely contributes.',
             None),
            ('the-tools',
             '',
             [
                ('🌊', 'WAVE (WebAIM)', 'Browser extension annotating the rendered page: errors, contrast, structural elements. Best for seeing problems IN CONTEXT on the page. Blind spots: no guided fixes, dynamic content needs re-triggering.'),
                ('🪓', 'axe DevTools (Deque)', 'Rule engine used by most CI pipelines; precise selectors and WCAG references per violation. Best for developers fixing issues. Free tier covers core rules; advanced rules paid.'),
                ('💡', 'Lighthouse (built into Chrome)', 'One-shot audit incl. accessibility score. Good baseline snapshot, but limited rule set and single-page only. Treat the score as a smoke test, never as conformance.'),
                ('🔍', 'Accessibility Insights for Web', 'Microsoft\'s extension: FastPass (automated + tab stops) plus Assessment (guided manual evaluation). The best free structured manual-testing framework.'),
                ('🗣️', 'NVDA / VoiceOver', 'Actual screen readers. Only way to experience what blind users get: heading navigation, form labels announced, focus order, alt-text quality. Automated tools cannot judge whether alt text MEANINGFUL, only whether present.'),
                ('⚡', 'Automated URL scanners', 'Crawl multiple pages unattended and aggregate violations — right shape for site-wide baselines and regression checks. Ours scans 16 WCAG 2.1 AA rules per page and flags exactly where each failure lives.'),
             ]),
            ('what-no-tool-catches',
             'Four failure classes evade every automated scanner. Alt-text quality: a tool sees presence, not senselessness. Keyboard traps in custom widgets: only Tab-through reveals them. Focus visibility during interaction: static analysis misses CSS :focus styles removed at runtime. And comprehension: logical heading structure, meaningful link text, sensible error messages. Budget manual time for these — an hour of keyboard-and-screen-reader testing finds more real barriers than another three scanners.',
             [
                ('⌨️', 'Keyboard pass', 'Tab through every interactive element. Can you reach, see, and operate everything? Escape closes modals? Focus never lost?'),
                ('🗣️', 'Screen reader spot-check', 'Navigate by headings, fill the contact form, submit it. Anything confusing to you is worse for daily screen-reader users.'),
                ('👀', 'Zoom test', '200% zoom and 400% reflow: nothing clipped, no horizontal scrolling required to read.'),
             ]),
            ('a-workflow-that-holds-up',
             'A sustainable cadence for a small team: (1) automated URL scan across key templates monthly — home, product/detail, article, form, search; (2) axe DevTools during development on every new component; (3) keyboard pass before each release on changed flows; (4) full Accessibility Insights Assessment quarterly; (5) screen-reader session quarterly on checkout/signup. Document results each cycle — regulators and enterprise buyers increasingly ask for evidence of testing, and a dated log of scans and fixes is that evidence.',
             None),
        ],
        faqs=[
            ('What is the best free accessibility checker?',
             'For a quick look: WAVE. For development work: axe DevTools. For structured manual evaluation: Accessibility Insights for Web. For whole-site coverage over time: an automated URL crawler. They answer different questions — most teams end up using two or three.'),
            ('Can Lighthouse scores prove EAA compliance?',
             'No. Lighthouse samples a subset of rules on one page load. Regulators look for EN 301 549/WCAG 2.1 AA conformance including manual criteria. A high score neither proves nor disproves it.'),
            ('Do I still need manual testing if all tools pass?',
             'Yes. Automated coverage tops out around 30–40% of WCAG success criteria. Alt-text quality, keyboard operability of custom widgets and comprehension require a human — see the section above on what no tool catches.'),
            ('How often should we scan?',
             'Monthly automated scans on core templates, plus a scan after every significant release. Quarterly manual passes. More frequent scanning costs little and catches regressions while the responsible code is still fresh.'),
        ],
        related_posts=[
            ('SCANNER · CLI', 'Accessibility Scanner CLI: Automate WCAG Checks', '/blog/accessibility-scanner-cli'),
            ('EAA · CHECKLIST', 'EAA Accessibility Checklist: 10 Steps', '/blog/eaa-accessibility-checklist'),
            ('AUDIT · COST', 'What Does an Accessibility Audit Cost?', '/blog/accessibility-audit-cost'),
            ('STATEMENTS', 'How to Write an Accessibility Statement', '/blog/how-to-write-accessibility-statement'),
        ],
    ),
]

for j in jobs:
    html = build_post(**j)
    path = f"site/blog/{j['slug']}.html"
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f'wrote {path} ({len(html)} bytes)')
