#!/usr/bin/env node
/**
 * sync_core.js — rebuilds site/clean-copy-core.js from the shared core +
 * pushes the core to obsidian + CLI copies.
 *
 * Does NOT touch extension background.js files: Chrome and Firefox have
 * diverged (Firefox has a process-pasted handler Chrome lacks), so they
 * must be kept in sync manually for the conversion functions. The test at
 * the end of tools/test_clean_copy.js verifies equality of htmlToMarkdown
 * between core and Chrome background.js at test time.
 *
 * Run: node tools/sync_core.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FULL = path.join(ROOT, 'tools/clean_copy_core.js'); // single source of truth
const CORE = path.join(ROOT, 'site/clean-copy-core.js');

let src = fs.readFileSync(FULL, 'utf8');
const umd = src.replace(
  ' * Extracted verbatim from the extension\'s background.js (same code the\n * Chrome/Firefox extensions run), so web tool and extension behave identically.',
  ' * GENERATED by tools/sync_core.js from tools/clean_copy_core.js.\n * Do not edit by hand \u2014 edit tools/clean_copy_core.js and re-run sync_core.js.'
);

fs.writeFileSync(CORE, umd);
// Obsidian plugin uses the exact same full core.
fs.writeFileSync(path.join(ROOT, 'obsidian-plugin/core.js'), umd);
// CLI keeps its own verbatim copy of the full core.
fs.copyFileSync(FULL, path.join(ROOT, 'clean-copy-cli/clean_copy_core.js'));
// Note: extension background.js files (Chrome, Firefox, repo) are NOT synced
// here because Firefox has a process-pasted handler Chrome lacks. Sync them
// manually when conversion functions change — tools/test_clean_copy.js will
// catch drift at test time.
console.log('synced: site core + obsidian + CLI core');
